import { Router, type IRouter } from "express";
import healthRouter        from "./health";
import usersRouter         from "./users";
import walletsRouter       from "./wallets";
import transactionsRouter  from "./transactions";
import tontinesRouter      from "./tontines";
import creditRouter        from "./credit";
import merchantsRouter     from "./merchants";
import complianceRouter    from "./compliance";
import analyticsRouter     from "./analytics";
import adminRouter         from "./admin";
import systemRouter        from "./system";
import sagasRouter         from "./sagas";
import riskRouter          from "./risk";
import webhooksRouter      from "./webhooks";
import fxRouter            from "./fx";
import settlementsRouter   from "./settlements";
import amlRouter           from "./aml";
import paymentRoutesRouter from "./paymentRoutes";
import connectorsRouter    from "./connectors";
import mqRouter            from "./mq";
import archiveRouter       from "./archive";
import clearingRouter     from "./clearing";
import multiRegionRouter  from "./multiRegion";
import fraudIntelRouter   from "./fraudIntel";
import regulatoryRouter   from "./regulatory";
import fxLiquidityRouter  from "./fxLiquidityRoute";
import securityRouter     from "./securityRoute";
import failureSimRouter   from "./failureSim";
import systemReportRouter from "./systemReport";
import walletProductRouter    from "./walletProduct";
import merchantProductRouter  from "./merchantProduct";
import developerRouter        from "./developer";
import productArchRouter      from "./productArchitecture";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users",          usersRouter);
router.use("/wallets",        walletsRouter);
router.use("/transactions",   transactionsRouter);
router.use("/tontines",       tontinesRouter);
router.use("/credit",         creditRouter);
router.use("/merchants",      merchantsRouter);
router.use("/compliance",     complianceRouter);
router.use("/analytics",      analyticsRouter);
router.use("/admin",          adminRouter);
router.use("/system",         systemRouter);
router.use("/sagas",          sagasRouter);
router.use("/risk",           riskRouter);
router.use("/webhooks",       webhooksRouter);
router.use("/fx",             fxRouter);
router.use("/settlements",    settlementsRouter);
router.use("/aml",            amlRouter);
router.use("/payment-routes", paymentRoutesRouter);
router.use("/connectors",     connectorsRouter);
router.use("/mq",             mqRouter);
router.use("/archive",        archiveRouter);
router.use("/clearing",       clearingRouter);
router.use("/regions",        multiRegionRouter);
router.use("/fraud/intel",    fraudIntelRouter);
router.use("/regulatory",     regulatoryRouter);
router.use("/fx/liquidity",   fxLiquidityRouter);
router.use("/security",       securityRouter);
router.use("/failure-sim",    failureSimRouter);
router.use("/system/report",  systemReportRouter);
router.use("/wallet",              walletProductRouter);
router.use("/merchant",            merchantProductRouter);
router.use("/developer",           developerRouter);
router.use("/product/architecture", productArchRouter);

export default router;
