import { Router, type IRouter } from "express";
import healthRouter        from "./health";
import usersRouter         from "./users";
import walletsRouter       from "./wallets";
import transactionsRouter  from "./transactions";
import tontinesRouter      from "./tontines";
import creditRouter        from "./credit";
import merchantsRouter     from "./merchants";
import complianceRouter    from "./compliance";
import analyticsRouter     from "./analytics";
import adminRouter         from "./admin";
import adminAuthRouter     from "./adminAuth";
import cashInRouter        from "./cashIn";
import systemRouter        from "./system";
import sagasRouter         from "./sagas";
import riskRouter          from "./risk";
import webhooksRouter      from "./webhooks";
import fxRouter            from "./fx";
import settlementsRouter   from "./settlements";
import amlRouter           from "./aml";
import paymentRoutesRouter from "./paymentRoutes";
import connectorsRouter    from "./connectors";
import mqRouter            from "./mq";
import archiveRouter       from "./archive";
import clearingRouter     from "./clearing";
import multiRegionRouter  from "./multiRegion";
import fraudIntelRouter   from "./fraudIntel";
import regulatoryRouter   from "./regulatory";
import fxLiquidityRouter  from "./fxLiquidityRoute";
import securityRouter     from "./securityRoute";
import failureSimRouter   from "./failureSim";
import { experimental } from "../middleware/experimental";
import { requireAdmin, gateWrites } from "../middleware/auth";
import systemReportRouter from "./systemReport";
import walletProductRouter    from "./walletProduct";
import merchantProductRouter  from "./merchantProduct";
import developerRouter        from "./developer";
import productArchRouter      from "./productArchitecture";
import communityFinanceRouter from "./communityFinance";
import investmentPoolsRouter  from "./investmentPools";
import insurancePoolsRouter   from "./insurancePools";
import savingsRouter          from "./savings";
import diasporaRouter         from "./diaspora";
import creatorEconomyRouter   from "./creatorEconomy";
import warroomRouter           from "./warroom";
import notificationsRouter     from "./notifications";
import agentsRouter            from "./agents";
import supportRouter           from "./support";
import authRouter              from "./auth";

const router: IRouter = Router();

router.use(healthRouter);
router.use("/users",          usersRouter);
router.use("/wallets",        walletsRouter);
router.use("/transactions",   transactionsRouter);
router.use("/tontines",       tontinesRouter);
router.use("/credit",         creditRouter);
router.use("/merchants",      merchantsRouter);
router.use("/compliance",     complianceRouter);
// Back-office and internal routers: every read needs an operator identity, every
// write needs the matching permission. Routers that already gate themselves
// (admin, aml, risk, compliance, …) are left as they are.
router.use("/analytics",      requireAdmin, analyticsRouter);
router.use("/admin/auth",     adminAuthRouter);
router.use("/admin/cash-in",  cashInRouter);
router.use("/admin",          adminRouter);
router.use("/system",         requireAdmin, systemRouter);
router.use("/sagas",          sagasRouter);
router.use("/risk",           riskRouter);
router.use("/webhooks",       webhooksRouter);
router.use("/fx",             fxRouter);
router.use("/settlements",    experimental("settlements"), requireAdmin, gateWrites("system.control"), settlementsRouter);
router.use("/aml",            amlRouter);
router.use("/payment-routes", requireAdmin, gateWrites("system.control"), paymentRoutesRouter);
router.use("/connectors",     experimental("connectors"), requireAdmin, gateWrites("system.control"), connectorsRouter);
router.use("/mq",             mqRouter);
router.use("/archive",        requireAdmin, gateWrites("system.control"), archiveRouter);
router.use("/clearing",       experimental("clearing"), requireAdmin, gateWrites("system.control"), clearingRouter);
router.use("/regions",        experimental("regions"), multiRegionRouter);
router.use("/fraud/intel",    requireAdmin, gateWrites("aml.review"), fraudIntelRouter);
router.use("/regulatory",     requireAdmin, gateWrites("aml.review"), regulatoryRouter);
router.use("/fx/liquidity",   requireAdmin, gateWrites("system.control"), fxLiquidityRouter);
router.use("/security",       securityRouter);
router.use("/failure-sim",    experimental("failure-sim"), failureSimRouter);
router.use("/system/report",  requireAdmin, systemReportRouter);
router.use("/wallet",              walletProductRouter);
router.use("/merchant",            merchantProductRouter);
router.use("/developer",           developerRouter);
router.use("/product/architecture", requireAdmin, productArchRouter);
router.use("/community",           communityFinanceRouter);
router.use("/pools/investment",    investmentPoolsRouter);
router.use("/pools/insurance",     insurancePoolsRouter);
router.use("/savings",             savingsRouter);
router.use("/diaspora",            diasporaRouter);
router.use("/creator",             creatorEconomyRouter);
router.use("/warroom",             requireAdmin, warroomRouter);
router.use("/notifications",       notificationsRouter);
router.use("/agents",              agentsRouter);
router.use("/support",             supportRouter);
router.use("/auth",                authRouter);

export default router;
